# chaos monkey
chaos.monkey.enabled=true

chaos.monkey.watcher.repository=true
chaos.monkey.assaults.level=1
chaos.monkey.assaults.latency-active=true
chaos.monkey.assaults.latency-range-start=100
chaos.monkey.assaults.latency-range-end=1000

chaos.monkey.assaults.kill-application-active=true

# actuator
management.endpoint.chaosmonkey.enabled=true
management.endpoint.chaosmonkeyjmx.enabled=true

management.endpoints.web.exposure.include=*
