# chaos monkey
chaos.monkey.enabled=true

chaos.monkey.watcher.bean-classes=com.pitachips.trxbatch.service.email.MonthlyTrxReportBulkEmailService

chaos.monkey.assaults.level=3
chaos.monkey.assaults.exceptions-active=true
chaos.monkey.assaults.deterministic=true
chaos.monkey.assaults.exception.type=com.pitachips.trxbatch.exceptions.TrxBatchEmailServerCommunicationException

# actuator
management.endpoint.chaosmonkey.enabled=true
management.endpoint.chaosmonkeyjmx.enabled=true

management.endpoints.web.exposure.include=*
